name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu:latest
    steps:
      - name: Test
        run: |
          apt install -y python3 p7zip-full build-essential ninja-build p7zip-full
          pip install -U frida frida-tools
          mkdir cmodule
          frida-create -t cmodule
      - name: Package Directories
        run: |
          7z a cmodule_armv8_example.7z ./cmodule
